Remove leading space when printing branches

diff --git a/rbm b/rbm
--- a/rbm
+++ b/rbm
@@ -71,11 +71,11 @@ if [ $failed_branches_num -eq 0 ]; then
 	git checkout "$orig_branch"
 elif [ $failed_branches_num -eq 1 ]; then
 	# If only one branch failed to rebase, offer to rebase interactively
-	printf >&2 'Rebase %s interactively? [y/N] ' "$failed_branches"
+	printf >&2 'Rebase %s interactively? [y/N] ' "${failed_branches# }"
 	read -r resp
 	case "${resp:-n}" in
 		Y*|y*)
-			git rebase -i master "$failed_branches"
+			git rebase -i master "${failed_branches# }"
 			;;
 		N*|n*)
 			git checkout "$orig_branch"
